# Generated by Django 5.2.4 on 2025-07-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("website", models.URLField(default="")),
                ("date_opened", models.DateField()),
                ("latitude", models.FloatField()),
                ("longtitude", models.FloatField()),
            ],
        ),
    ]
